apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
    - name: nginx-app 
      image: basm16/nginx-task
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80